version: '3.4'

services:
  db:
    container_name: "lab-03-db"
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
      
    env_file:
      - ./db-local.env
    environment:
      MSSQL_PID: "Express"
      ACCEPT_EULA: "Y"

  app:
    image: "pokhylenkoregistry.azurecr.io/todo-app:v1"
    container_name: "lab-03-app"
    depends_on:
      - db
    ports:
      - "5000:80"
    env_file:
      - ./app-local.env
